;设置规则标志位
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
;surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/useesee/subconverter/master/LocalAreaNetwork.list
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/useesee/subconverter/master/cusDirect.list
;surge_ruleset=🔥 应用净化,https://anti-ad.net/surge.txt
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-quanx.txt
; 使用上面一条替代全部
surge_ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
surge_ruleset=🛑 全球拦截,https://raw.githubusercontent.com/useesee/subconverter/master/cusDeny.list
surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Bilibili.conf
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Applet.conf
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Netease.conf
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Amap.conf
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/YoutubeAds.conf
;surge_ruleset=🔥 应用净化,https://gist.githubusercontent.com/ddgksf2013/beec132ca0c3570ffa0cf331bce8f82a/raw/baidumap.adblock.conf
;surge_ruleset=🔥 应用净化,https://gist.githubusercontent.com/ddgksf2013/f43026707830c7818ee3ba624e383c8d/raw/baiduCloud.vip.js
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/ddgksf2013/Scripts/master/12306.js
;surge_ruleset=🔥 应用净化,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zheye/zheye.snippet
surge_ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
surge_ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
surge_ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
surge_ruleset=🔘 环球飞行,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
# surge_ruleset=📢 谷歌推送,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
surge_ruleset=🔘 环球飞行,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
surge_ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
surge_ruleset=🤖 人工智能,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
surge_ruleset=🤖 人工智能,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
surge_ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
;surge_ruleset=🎼 TikTok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
surge_ruleset=🐉 华夏之声,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
surge_ruleset=🌍 环球视听,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
surge_ruleset=🔘 环球飞行,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
surge_ruleset=🐉 华夏之声,https://raw.githubusercontent.com/useesee/subconverter/master/cusDomestic.list
surge_ruleset=💠 三方跳动,https://raw.githubusercontent.com/useesee/subconverter/master/cusOth.list
surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/O7Y0/Attached/main/UnblockNeteaseMusic/NeteaseCloudMusic.list
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/useesee/subconverter/master/ease.list
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/PoetryU/Scientist/master/Profiles/Rules/NeteaseMusic.yaml
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/GlitterZero/Scripts/NeteaseMusic/NeteaseMusic.list
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/DesperadoJ/Rules-for-UnblockNeteaseMusic/master/Clash/RuleSet/NeteaseMusic.yaml
;surge_ruleset=🎵 网易音乐,https://raw.githubusercontent.com/ddgksf2013/Filter/master/NeteaseMusic.list
;surge_ruleset=📽️ Emby影音,https://raw.githubusercontent.com/useesee/subconverter/master/Emby.list
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
surge_ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
surge_ruleset=🎯 全球直连,[]GEOIP,CN
surge_ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
;custom_proxy_group=🔘 环球飞行`select`[]🌞 群组故障`[]⛄ 群组延时`[]👻 故障切换`[]⏱️ 延时切换`[]🎡 负载均衡`[]🚁中继延时`[]🇺🇲 美国延时`[]🇭🇰 香港延时`[]🇸🇬 新加坡延时`[]🇯🇵 日本延时`^((?!.*(解锁|群)).)*$
;custom_proxy_group=🔘 环球飞行`select`[]🌞 群组故障`[]⛄ 群组延时`[]👻 故障切换`[]⏱️ 延时切换`[]🎡 负载均衡`[]🇺🇲 美国延时`[]🇭🇰 香港延时`[]🇸🇬 新加坡延时`[]🇯🇵 日本延时`^((?!.*(解锁|群|免费)).)*$
;custom_proxy_group=🔘 环球飞行`select`[]🇺🇲 美国延时`[]🇸🇬 新加坡延时`[]🇷🇺 俄罗斯延时`[]🚁 天机智由`[]🎡 负载均衡`^((?!.*(解锁|群|免费|网易|数值|M0NATA)).)*$`[]DIRECT
custom_proxy_group=🔘 环球飞行`select`[]🚁 天机智由`[]🎡 负载均衡`^((?!.*(解锁|群|免费|网易|数值|M0NATA)).)*$`[]DIRECT
custom_proxy_group=🚁 天机智由`url-test`^((?!.*(解锁|群|暂|免费|网易|数值|M0NATA)).)*$`http://www.gstatic.com/generate_204`200,,50
;custom_proxy_group=🌞 群组故障`fallback`[]🇺🇲 美国延时`[]🇭🇰 香港延时`[]🇸🇬 新加坡延时`[]🇯🇵 日本延时`http://www.gstatic.com/generate_204`200
;custom_proxy_group=⛄ 群组延时`url-test`[]🇺🇲 美国延时`[]🇭🇰 香港延时`[]🇸🇬 新加坡延时`[]🇯🇵 日本延时`http://www.gstatic.com/generate_204`200
;custom_proxy_group=👻 故障切换`fallback`^((?!.*(解锁|群|暂|免费)).)*$`http://www.gstatic.com/generate_204`200
;custom_proxy_group=🇺🇲 美国延时`url-test`^(?!.*中).*(美)`http://www.gstatic.com/generate_204`200
;custom_proxy_group=🇸🇬 新加坡延时`url-test`^(?!.*中).*(新)`http://www.gstatic.com/generate_204`200
;custom_proxy_group=🇷🇺 俄罗斯延时`url-test`^(?!.*中).*(俄)`http://www.gstatic.com/generate_204`200
;custom_proxy_group=🇯🇵 日本延时`url-test`^(?!.*中).*(日)`http://www.gstatic.com/generate_204`200
;custom_proxy_group=🚁中继延时`url-test`^(?!.*暂).*(中)`http://www.gstatic.com/generate_204`200
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🔘 环球飞行
custom_proxy_group=🤖 人工智能`select`[]🔘 环球飞行`^((?!.*(解锁|群|免费|网易|数值|M0NATA)).)*$
custom_proxy_group=💠 三方跳动`select`[]🎯 全球直连`[]🔘 环球飞行
custom_proxy_group=🐉 华夏之声`select`[]🎯 全球直连`[]🔘 环球飞行
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🔘 环球飞行
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🔘 环球飞行
custom_proxy_group=🎵 网易音乐`select`(解锁|网易|M0NATA|数值)`[]🎯 全球直连
;custom_proxy_group=📽️ Emby影音`select`[]🎯 全球直连`[]🔘 环球飞行
custom_proxy_group=🌍 环球视听`select`[]🔘 环球飞行`[]🎯 全球直连
# custom_proxy_group=📢 谷歌推送`select`[]🔘 环球飞行`[]🎯 全球直连
# custom_proxy_group=🎅 谷歌直连`select`[]🔘 环球飞行`[]🎯 全球直连
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🔘 环球飞行
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]🎯 全球直连
custom_proxy_group=🔥 应用净化`select`[]REJECT`[]🎯 全球直连
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]🎯 全球直连
custom_proxy_group=🎡 负载均衡`load-balance`^((?!.*(解锁|群|暂|免费|网易|数值|M0NATA)).)*$`http://www.gstatic.com/generate_204`200
;设置分组标志位
